name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Udemy - 100 Days of Code The Complete Python Pro Bootcamp"
  comment: "Web Developer"
  url: "https://d4130.download-send.com/d/izywt55w6gosj4l4qv4qfevh2ddb3kklyxqytfh3tlgvipqtyt73isch66eczoa4ew6oftkk/Udemy%20-%20100%20Days%20of%20Code%20The%20Complete%20Python%20Pro%20Bootcamp%20(2024-3).part1.rar"
  file_name: "Udemy - 100 Days of Code The Complete Python Pro Bootcamp (2024-3).part1.rar"
  piece_size: 2^22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
